server:
  port: 8081
  ssl:
    "key-store" : 'classpath:server.jks'
    "key-store-password" : s3cr3t
    "key-password" : s3cr3t
    "trust-store" : 'classpath:server_trust.jks'
    "trust-store-password" : s3cr3t
    "client-auth" : "need"